#!/usr/bin/env python3
"""A generated entry point to the graph: where to start, and how much to trust it.

`graph.html` shows you everything and `standup` shows you what needs you. Neither
answers the questions someone asks when they first meet the graph, or when they
come back to it after a paper is written:

- **Where do I start?** Which nodes is everything else hanging off.
- **What connects things I didn't expect?** A typed relation between two
  different projects is the hardest edge to reconstruct later and the easiest to
  forget exists.
- **How much can I trust a gap?** `CLAUDE.md` says to read a missing node as "not
  tried" only where the project is well covered — and nothing computed coverage,
  so that instruction had no way to be followed.
- **Was this written at the time, or reconstructed afterwards?** A claim recorded
  the day the job finished is stronger evidence than one written from memory six
  weeks later. Both are worth having; conflating them is not.

That last one is the idea worth taking from Graphify, whose every edge carries
`EXTRACTED` (read from the source) or `INFERRED` (resolved by the tool) so you
always know what was found versus guessed. The same distinction matters here and
is *already derivable*: git knows when the file was committed, the frontmatter
says when the work happened, and the difference is capture lag. So it costs no
field, which is the only reason it belongs — see the resist-new-fields rule.

    cairn report                  # write build/report.md
    cairn report --stdout         # print it instead
    cairn report --project polyid # one project

Regenerated by `make build`, like everything else under `build/`. It is derived,
so it can be deleted; nothing reads it back.
"""

from __future__ import annotations

import argparse
import datetime as dt
import subprocess
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import lib

#: Lag past which a node reads as reconstruction rather than record. Chosen to be
#: forgiving: a node committed within a working week of the work is a record
#: someone got round to pushing, not a memory.
LAG_DAYS = 7

#: How many rows each section shows. A report nobody scrolls is a report nobody
#: reads, and the map is the right tool for exhaustive.
TOP = 12


def commit_dates() -> dict[str, dt.date]:
    """Node id -> the date its file first appeared in a commit.

    One `git log` for the directory, same as `node_authors` in build_graph and
    for the same reason: one subprocess, not one per node.
    """
    try:
        done = subprocess.run(
            ["git", "-C", str(lib.REPO_ROOT), "log", "--reverse", "--diff-filter=A",
             "--format=%x00%ad", "--date=short", "--name-only", "--", "nodes"],
            capture_output=True, text=True, timeout=60,
        )
    except (OSError, subprocess.SubprocessError):
        return {}
    if done.returncode != 0:
        return {}
    out: dict[str, dt.date] = {}
    for chunk in done.stdout.split("\x00"):
        lines = [line for line in chunk.splitlines() if line.strip()]
        if not lines:
            continue
        when = lib.as_date(lines[0])
        if when is None:
            continue
        for path in lines[1:]:
            out.setdefault(Path(path).stem, when)
    return out


def degree(nodes: dict[str, lib.Node]) -> dict[str, int]:
    """Total edges touching each node: lineage both ways, plus typed relations."""
    kids = lib.children_of(nodes)
    inbound = lib.relation_backlinks(nodes)
    return {
        node_id: (len(node.parents) + len(kids.get(node_id, []))
                  + len(node.relates) + len(inbound.get(node_id, [])))
        for node_id, node in nodes.items()
    }


def coverage(nodes: dict[str, lib.Node], lag: dict[str, int],
             review: dict[str, dict] | None = None) -> list[dict]:
    """Per-project: how much is here, and how much of it was written at the time.

    The point of this table is a single instruction in CLAUDE.md that was
    previously unfollowable: treat a missing node as "not tried" only where the
    project is well covered. "Well covered" needs a number, and the honest
    number is two — how many nodes, and what fraction were recorded
    contemporaneously rather than reconstructed.
    """
    review = review if review is not None else {}
    by_project: dict[str, list[lib.Node]] = {}
    for node in nodes.values():
        by_project.setdefault(node.project or "(unassigned)", []).append(node)

    rows = []
    for project, members in sorted(by_project.items()):
        settled = [n for n in members if n.is_terminal]
        dead = [n for n in members if n.status in ("dead", "killed", "dropped")]
        lags = [lag[n.id] for n in members if n.id in lag]
        fresh = [d for d in lags if d <= LAG_DAYS]
        spans = [n.created for n in members if n.created]
        # Only nodes git can actually classify go in the denominator. A node
        # written before the convention existed is not evidence of a review that
        # did not happen, and folding it in as a miss would make the number a
        # complaint about history rather than a measurement.
        known = [review[n.id]["state"] for n in members
                 if review.get(n.id, {}).get("state") in ("reviewed", "unreviewed")]
        read = [s for s in known if s == "reviewed"]
        rows.append({
            "project": project,
            "total": len(members),
            "settled": len(settled),
            "dead": len(dead),
            "contemporaneous": (len(fresh) / len(lags)) if lags else None,
            "reviewed": (len(read) / len(known)) if known else None,
            "unclassified": len(members) - len(known),
            "first": min(spans) if spans else None,
            "last": max(spans) if spans else None,
        })
    rows.sort(key=lambda r: -r["total"])
    return rows


def cross_project(nodes: dict[str, lib.Node]) -> list[tuple]:
    """Typed relations and lineage edges that cross a project boundary.

    Graphify calls these "surprising connections" and ranks them by surprise.
    Here the definition can be exact rather than heuristic: the README says
    cross-project edges are the hardest part of the record to reconstruct, so
    an edge whose two ends sit in different projects is *by construction* the
    thing worth listing.
    """
    out = []
    for node in nodes.values():
        for rel in node.relates:
            other = nodes.get(str(rel.get("to")))
            if other is not None and other.project != node.project:
                out.append((node, str(rel.get("type", "")), other,
                            str(rel.get("note", ""))))
        for parent in node.parents:
            other = nodes.get(parent)
            if other is not None and other.project != node.project:
                out.append((node, "derives from", other, ""))
    out.sort(key=lambda row: row[0].id, reverse=True)
    return out


def build(nodes: dict[str, lib.Node], project: str) -> str:
    if project:
        nodes = {k: v for k, v in nodes.items() if v.project == project}

    commits = commit_dates()
    lag = {}
    for node in nodes.values():
        when, committed = node.created, commits.get(node.id)
        if when and committed:
            lag[node.id] = max(0, (committed - when).days)

    deg = degree(nodes)
    kids = lib.children_of(nodes)
    scope = f" — {project}" if project else ""
    lines = [
        f"# Cairn report{scope}",
        "",
        f"Generated {dt.date.today().isoformat()} from {len(nodes)} node(s). "
        "Derived — never hand-edit; `make build` regenerates it.",
        "",
        "This is the entry point, not the graph. `build/graph.html` is the map, "
        "`cairn standup` is what needs you today, and this answers *where to "
        "start* and *how much to trust a gap*.",
    ]

    # ---- Hubs -------------------------------------------------------------
    hubs = sorted(nodes.values(), key=lambda n: (-deg[n.id], n.id))[:TOP]
    if hubs and deg[hubs[0].id]:
        lines += ["", "## Start here", "",
                  "The most-connected nodes. Everything else hangs off these, so "
                  "reading them first is the cheapest way into a project — and "
                  "changing what one of them claims is the change with the widest "
                  "blast radius.", ""]
        for node in hubs:
            if not deg[node.id]:
                continue
            lines.append(
                f"- **{node.title}** — {deg[node.id]} edge(s) · `{node.status}` · "
                f"{node.project} · `{node.id}`")

    # ---- Cross-project ----------------------------------------------------
    crossing = cross_project(nodes)
    if crossing:
        lines += ["", "## Connections across projects", "",
                  "Edges whose two ends sit in different projects. These are the "
                  "hardest part of the record to reconstruct from anything else — "
                  "a project repo cannot know about them — so they are the reason "
                  "the graph is one graph and not one per project.", ""]
        for node, kind, other, note in crossing[:TOP]:
            lines.append(f"- **{node.project} → {other.project}** — "
                         f"*{node.title}* {kind} *{other.title}*")
            if note:
                lines.append(f"  - {note}")

    # ---- Coverage ---------------------------------------------------------
    review = lib.review_states(nodes)
    rows = coverage(nodes, lag, review)
    lines += ["", "## Coverage, and what a gap means", "",
              "`CLAUDE.md` says to read a missing node as \"not tried\" only where "
              "a project is well covered. That needs a number, and the honest one "
              "is two: how much is recorded, and how much of it was written *at "
              "the time* rather than reconstructed afterwards.", "",
              "| project | nodes | settled | dead ends | written at the time | "
              "read by a human | span |",
              "|---|---:|---:|---:|---:|---:|---|"]
    for row in rows:
        share = ("—" if row["contemporaneous"] is None
                 else f"{row['contemporaneous'] * 100:.0f}%")
        seen = ("—" if row["reviewed"] is None
                else f"{row['reviewed'] * 100:.0f}%")
        span = (f"{row['first']} → {row['last']}"
                if row["first"] and row["last"] else "—")
        lines.append(f"| {row['project']} | {row['total']} | {row['settled']} | "
                     f"{row['dead']} | {share} | {seen} | {span} |")
    lines += ["",
              f"*Written at the time* means the node's file was committed within "
              f"{LAG_DAYS} days of the date it claims the work happened. A low "
              "share is not a fault — the backfill was deliberate and is what "
              "made the graph useful on day one — but it does mean those nodes "
              "are a reconstruction, and a reconstruction is biased toward what "
              "worked. Read a gap in a thin or heavily-backfilled project as "
              "\"the graph doesn't know\", not as \"nobody tried it\"."]

    stale = sum(row["unclassified"] for row in rows)
    if stale:
        lines += ["",
                  "*Read by a human* is derived from `Cairn-Review:` trailers in "
                  "the git log, so it can only speak about nodes written after "
                  f"that convention existed. **{stale} node(s) predate it** and "
                  "are left out of the column rather than counted as unread — git "
                  "has nothing to say about them either way. `cairn review --list` "
                  "is the working queue."]

    # ---- Reconstructions --------------------------------------------------
    late = sorted(((days, nodes[i]) for i, days in lag.items() if days > LAG_DAYS),
                  key=lambda pair: -pair[0])[:TOP]
    if late:
        lines += ["", "## Reconstructed after the fact", "",
                  "Written down well after the work. Worth having and worth "
                  "flagging: the interpretation in these was formed with the "
                  "result already known.", ""]
        for days, node in late:
            lines.append(f"- **{days}d later** — {node.title} "
                         f"(`{node.project}` · `{node.id}`)")

    # ---- Loose ends -------------------------------------------------------
    orphans = [n for n in nodes.values()
               if not n.parents and not kids.get(n.id) and not n.relates
               and n.type != "direction"]
    if orphans:
        lines += ["", "## Unattached", "",
                  "No parent, no child, no relation, and not a `direction` — which "
                  "is the one type that is allowed to stand alone. Usually a node "
                  "whose lineage was never filled in, occasionally a real "
                  "one-off. Either way nobody will find these by navigating.", ""]
        for node in sorted(orphans, key=lambda n: n.id, reverse=True)[:TOP]:
            lines.append(f"- {node.title} (`{node.project}` · `{node.status}` · "
                         f"`{node.id}`)")

    # ---- Notes ------------------------------------------------------------
    unanswered = []
    for node in nodes.values():
        last = node.updated or node.created
        for note in lib.read_notes(node):
            when = note.get("date")
            if when is None or last is None or when >= last:
                unanswered.append((when or dt.date.min, node, note))
    if unanswered:
        unanswered.sort(key=lambda row: row[0], reverse=True)
        lines += ["", "## Notes nobody has answered", ""]
        for when, node, note in unanswered[:TOP]:
            who = f" ({note['who']})" if note["who"] else ""
            lines.append(f"- **{when}**{who} on *{node.title}* — {note['text']}")
            lines.append(f"  - `{node.id}`")

    # ---- What the graph can be asked --------------------------------------
    types = Counter(n.type for n in nodes.values())
    statuses = Counter(n.status for n in nodes.values())
    lines += ["", "## Shape", "",
              "- types: " + ", ".join(f"{k} {v}" for k, v in types.most_common()),
              "- statuses: " + ", ".join(f"{k} {v}" for k, v in statuses.most_common()),
              f"- dead ends: {statuses['dead'] + statuses['killed'] + statuses['dropped']}"
              " — the nodes ordinary git workflow is designed to garbage-collect, "
              "and the ones that make a methods section writable."]
    return "\n".join(lines) + "\n"


def main() -> int:
    p = argparse.ArgumentParser(
        prog="cairn report",
        description="Generate build/report.md — where to start, and what a gap means.")
    p.add_argument("--project", default="", help="restrict to one project key")
    p.add_argument("--stdout", action="store_true", help="print instead of writing")
    args = p.parse_args()

    nodes, errors = lib.load_nodes()
    for error in errors:
        print(f"cairn: {error}", file=sys.stderr)
    if not nodes:
        print("cairn: no nodes", file=sys.stderr)
        return 1

    text = build(nodes, args.project)
    if args.stdout:
        print(text, end="")
        return 0

    target = lib.REPO_ROOT / "build" / ("report.md" if not args.project
                                        else f"report-{args.project}.md")
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text, encoding="utf-8")
    print(f"{target.relative_to(lib.REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
